//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tukhvatullina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.Painting_artist = new HashSet<Painting_artist>();
        }
    
        public int ID_artist { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public Nullable<System.DateTime> Date_death { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Painting_artist> Painting_artist { get; set; }
    }
}
