//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tukhvatullina
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtistEntities2 : DbContext
    {
        public ArtistEntities2()
            : base("name=ArtistEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Avtorization> Avtorization { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Institution> Institution { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Painting_artist> Painting_artist { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_exhibition> Type_exhibition { get; set; }
        public virtual DbSet<Type_owner> Type_owner { get; set; }
    }
}
