//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tukhvatullina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int ID_owner { get; set; }
        public string Name { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> ID_Hall { get; set; }
        public Nullable<int> ID_type_owner { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Type_owner Type_owner { get; set; }
    }
}
