//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tukhvatullina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting_artist
    {
        public int ID_painting_artist { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Creation_date { get; set; }
        public string Execution { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> ID_artist { get; set; }
        public Nullable<int> ID_exhibition { get; set; }
        public Nullable<int> ID_Hall { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Exhibition Exhibition { get; set; }
        public virtual Hall Hall { get; set; }
    }
}
